Policy Tracker/Policy Tracker/Controllers/PolicyController.cs
using DevExpress.Web.Mvc;

using PolicyTracker.BusinessServices;
using PolicyTracker.DataAccess;
using PolicyTracker.DataAccess.WCPostingNotice;
using PolicyTracker.DomainModel;
using PolicyTracker.DomainModel.Brokers;
using PolicyTracker.DomainModel.Common;
using PolicyTracker.DomainModel.Framework;
using PolicyTracker.DomainModel.Policy;
using PolicyTracker.DomainModel.Security;
using PolicyTracker.Filters;
using PolicyTracker.Platform.Security;
using PolicyTracker.Platform.UOW;
using PolicyTracker.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Text;
using PolicyTracker.DomainModel.PostNotice;

namespace PolicyTracker.Controllers
{
    public class PolicyController : BaseController
    {
        /// <summary>
        /// Build the necessary view data for the Risk Entry and Risk Edit Forms.
        /// </summary>
        /// <param name="risk">Risk being entered</param>
        private void RiskViewData(Risk risk)
        {
            var productLines = ServiceLocator.EntityService.GetList<ProductLine>();

            ViewBag.ProductLines = productLines;
            ViewBag.Products = ServiceLocator.EntityService.GetList<Product>(new PropertyFilter("IsActive", true));
            ViewBag.Branches = StringEnum.GetAll<Branch>();
            ViewBag.States = ServiceLocator.BrokerSvc.GetStates();
            ViewBag.AircraftUses = ServiceLocator.EntityService.GetList<PurposeOfUse>(new PropertyFilter("IsActive", true));
            ViewBag.Statuses = new List<RiskStatus>() { RiskStatus.INVOLVED, RiskStatus.SUBMISSION };
            ViewBag.Underwriters = ServiceLocator.RiskService.GetUnderwriters();
            ViewBag.Agents = ServiceLocator.BrokerSvc.GetAgentsForBroker(risk.AgencyID);
        }

        /// <summary>
        /// Build the Additional View data elements required for the Risk Edit Form. This is not necessary for Risk Entry due to the simplified amount of entry points in the Risk Entry/Submission Process
        /// </summary>
        /// <param name="risk">Risk Being Edited</param>
        private void RiskEditFormViewData(Risk risk)
        {
            var productLines = ServiceLocator.EntityService.GetList<ProductLine>();
            ViewBag.WCProductLineId = productLines.Where(x => x.Name == "Workers Comp").First().ProductLineId;
            //Filter by Status Unsuccessful due to how Ravent initially setup this table. I wanted to use it instead of creating a new one.
            var markets = ServiceLocator.EntityService.GetList<Market>(new PropertyFilter("Status", PropertyFilter.Comparator.Equals, "Unsuccessful")).ToList();
            markets.Insert(0, new Market() { Id = 0, CompanyName = "" });
            ViewBag.Markets = markets;
            ViewBag.StatusReasons = ServiceLocator.PolicySvc.GetStatusReasons(risk.Status);
            ViewBag.WCPrograms = StringEnum.GetAll<WorkCompProgramType>();
            ViewBag.WCAccountDescs = StringEnum.GetAll<WorkCompAccountDesc>();

            var broker = ServiceLocator.EntityService.GetInstance<Broker>(new PropertyFilter("AgencyID", risk.AgencyID));
            var brokerMailing = ServiceLocator.EntityService.GetInstance<BrokerMailingAddress>(new PropertyFilter("AgencyID", risk.AgencyID));
            ViewBag.Broker = (broker == null) ? new Broker() { AgencyName = "", State = "" } : broker;
            ViewBag.BrokerMailing = (brokerMailing == null) ? new BrokerMailingAddress() { State = "" } : brokerMailing;

            ViewBag.IsLicensed = ServiceLocator.BrokerSvc.IsBrokerLicensedAlert(risk);
            ViewBag.Agents = ServiceLocator.BrokerSvc.GetAgentsForBroker(risk.AgencyID);
            ViewBag.Assistants = ServiceLocator.RiskService.GetUnderwritingAssistants();

            ViewBag.Statuses = StringEnum.GetAll<RiskStatus>().ToList();
        }

        /// <summary>
        /// Gets the availble list of statuses based on the current status of the Risk being entered/edited. Currently we allow any status if the risk is being edited to make things easier.
        /// </summary>
        /// <param name="status">Current Risk Status</param>
        /// <param name="statuses">List of Availble statuses</param>
        /// <param name="isEdit">Is Risk Being Edited</param>
        /// <returns>List of availble status choices</returns>
        public List<RiskStatus> GetStatusList(string status, List<RiskStatus> statuses, bool isEdit)
        {
            switch (status)
            {
                case "Submission":
                    statuses = new List<RiskStatus>() { RiskStatus.INVOLVED, RiskStatus.SUBMISSION, RiskStatus.DECLINED };
                    break;
                default:
                    statuses = StringEnum.GetAll<RiskStatus>().ToList();
                    break;
            }
            if (isEdit) statuses = StringEnum.GetAll<RiskStatus>().ToList();
            return statuses;
        }

        public ActionResult ClearanceSearch()
        {
            return PartialView();
        }

        public ActionResult RiskPreview(int riskId, string context)
        {
            var risk = ServiceLocator.RiskService.GetRisk(riskId);
            ViewBag.ProductLine = ServiceLocator.EntityService.GetInstance<ProductLine>(new PropertyFilter("ProductLineId", risk.ProductLine));
            var uw = ServiceLocator.EntityService.GetInstance<User>(new PropertyFilter("UserId", risk.UnderwriterId));
            ViewBag.UWName = (uw != null) ? uw.Name : "NOT ASSIGNED";
            var relatedRisk = ServiceLocator.EntityService.GetInstance<Risk>(new PropertyFilter("Id", risk.ParentID));
            ViewBag.RelatedRisk = relatedRisk;
            var broker = ServiceLocator.EntityService.GetInstance<BrokerMailingAddress>(new PropertyFilter("AgencyID", risk.AgencyID));
            ViewBag.BrokerState = (broker != null) ? broker.State : "";
            ViewBag.Logs = ServiceLocator.EntityService.GetList<RiskLog>(new PropertyFilter("RiskId", riskId));
            //risk.Aircrafts = ServiceLocator.EntityService.GetList<Aircraft>(new PropertyFilter("QuoteId", risk.Id)).ToList();
            if (relatedRisk != null)
            {
                var relatedUW = ServiceLocator.EntityService.GetInstance<User>(new PropertyFilter("UserId", relatedRisk.UnderwriterId));
                ViewBag.RealtedRiskUW = (relatedUW != null) ? relatedUW.Name : "";
            }
            ViewBag.PreviewParent = context;
            return PartialView(risk);
        }

        [HttpGet]
        public ActionResult RiskEntryForm(int controlNumber = 0)
        {
            var model = ServiceLocator.RiskService.GetNewRisk(controlNumber);
            RiskViewData(model);
            return PartialView(model);
        }

        [HttpPost]
        [UseTransaction]
        public ActionResult RiskEntryForm(Risk entity)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (entity.Id != 0) entity = ServiceLocator.RiskService.GetRisk(entity.Id);
                    entity = WebUtils.FormDataToModel<Risk>(entity, Request.Form);

                    if (entity.Id != 0)
                        ServiceLocator.PolicySvc.EntrySaveExisting(entity);
                    else
                        ServiceLocator.PolicySvc.SaveNewRisk(entity);
                    ModelState.Clear();
                }
                catch (ValidationRulesException ex)
                {
                    ProcessValidationException(ex);
                }
            }

            RiskViewData(entity);
            return PartialView(entity);
        }

        public ActionResult NoteForm(int riskId, int noteId = 0)
        {
            var note = new RiskNote() { RiskId = riskId };
            if (noteId != 0) note = ServiceLocator.EntityService.GetInstance<RiskNote>(new PropertyFilter[] { new PropertyFilter("RiskId", riskId), new PropertyFilter("Id", noteId) });
            return PartialView(note);
        }

        [HttpPost]
        [UseTransaction]
        public ActionResult NoteForm(RiskNote entity)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    entity = BindRequestToEntity<RiskNote>(entity, new PropertyFilter("Id", entity.Id));
                    ServiceLocator.RiskService.SaveNote(entity);
                    ModelState.Clear();
                }
                catch (ValidationRulesException ex)
                {
                    ProcessValidationException(ex);
                }
            }

            return PartialView(entity);
        }

        public ActionResult CommercialRatingApp(int id)
        {
            var model = ServiceLocator.EntityService.GetInstance<Risk>(new PropertyFilter("Id", id));
            ServiceLocator.PolicySvc.PrepareRiskForCommApp(model);
            return PartialView(model);
        }

        [HttpGet]
        public ActionResult RiskEditForm(int id)
        {
            var model = ServiceLocator.RiskService.GetRisk(id);

            //get collection of Locations for List Box View in Main Insured WC OpitionList
            List<WCPnLocationDomain> locations = new List<WCPnLocationDomain>();
            locations = WCPNServiceDAOCalls.View.getAlllocations(id);
            model.MainLocationsOptionList = new MultiSelectList(locations, "Id", "Name");

            //Load Selected Mapped Data
            //Get all assigned Locations mapped to QuoteId, AdditionalNamedInsuredId
            List<WCPnLocationDomain> selectedlocations = new List<WCPnLocationDomain>();
            selectedlocations = WCPNServiceDAOCalls.View.getMainInsuredLocations(id);
            //Add location items to int Array List
            var itemList = new List<int>();
            for (int i = 0; i < selectedlocations.Count; i++)
            {
                itemList.Add(selectedlocations[i].Id);
            }

Policy Tracker/Policy Tracker/Views/Home/ExportStats.cshtml
@model HtmlEditorSettings

@Html.DevExpress().HtmlEditor(Model).GetHtml()

Policy Tracker/Policy Tracker/Views/Home/GridConfigList.cshtml
<div class="dropdown gridMenu">
    <button class="btn btn-primary dropdown-toggle" type="button" id="testtest" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" >
        @foreach(var config in ViewBag.GridConfigs)
        {
            <li><a href="#" ora-grid-config="@config.Name" class="gridConfigLink">@config.Name</a></li>
        }
    </ul>
</div>

<script type="text/javascript">
    $(".gridConfigLink").each(function () {
        $(this).click(function (e) {
            e.preventDefault();
            var config = $(this).attr('ora-grid-config');
            ora.Ajax.Ajax({
                url: '/policytracker/home/WorkingList?gridConfig=' + config, type: 'GET', dataType: 'HTML',
                successCallback: function (html) {
                    $("#page-wrapper").html(html);
                    var commandMenuHeight = $('#WorkingListCommandMenu').height();
                    var height = $('#page-wrapper').height();
                    WorkingListGrid.SetHeight(height - 93 - (commandMenuHeight - 34));
                    var containerWidth = $('#page-wrapper').width();
                    WorkingListGrid.SetWidth(containerWidth);
                }
            });
        });
    });
</script>

Policy Tracker/Policy Tracker/Views/Home/Index.cshtml
@if (!SecurityManager.HasAccess("/Risk/WorkingList", SecurityManager.ResourcePrivilege.Read))
{
    Html.RenderAction("ClearanceSearch", "Policy");
    <script type="text/javascript">
        $(document).ready(function () {
            $("#NewRiskEntryButton").click(function () {
                ora.Dialog.ActionForm(
                {
                    id: 'NewRiskEntry_dg',
                    title: 'Risk Entry',
                    form: {
                        id: "RiskEntryForm",
                        container: "NewRiskEntry_dg",
                        dialog: "NewRiskEntry_dg",
                        submitURL: "policytracker/Policy/RiskEntryForm",
                        grid: "NamedInsuredSearchGrid"
                    },
                    url: "policytracker/Policy/RiskEntryForm",
                    modal: true, autoFocus: "PolicyType",
                    WritePermissions: true,
                    Type: ora.Dialog.ActionFormSizes.Large,
                });
            });
        });
    </script>
}
else
{
    Html.RenderAction("WorkingList", "Home");
}

Policy Tracker/Policy Tracker/Views/Home/QuickAssign.cshtml
@model PolicyTracker.DTO.UnderwriterQuickAssign

<script type="text/javascript">
    $(document).ready(function () {
        $("#QuickAssignForm").submit(function (event) {
            event.preventDefault();
            ora.Ajax.FormPost(
            {
                url: "/PolicyTracker/Home/QuickAssign",
                container: "QuickAssign_dg",
                grid: "",
                form: "QuickAssignForm",
                data: $("#QuickAssignForm").serializeArray(),
                PreventDefault: true,
                dialog: "QuickAssign_dg",
                successCallback: function () {
                    $("#WLRefresh").click();
                }
            })
        });
    });
</script>

<form id="QuickAssignForm" class="oraForm">
    <div class="row">
        @Html.ValidationSummary()
    </div>

    @Html.HiddenFor(m => Model.Id)

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary borderless">
                <div class="panel-body gray">
                    <div class="form-group">
                        <label>Underwriter:</label>
                        @Html.DropDownListFor(m => Model.UnderwriterId, new SelectList(ViewBag.Underwriters, "UserId", "Name"), "", new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label>Underwriter Assistant:</label>
                        @Html.DropDownListFor(m => Model.UnderwriterAssistantId, new SelectList(ViewBag.Assistants, "UserId", "Name"), "", new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Policy Tracker/Policy Tracker/Views/Home/SaveFilterSettings.cshtml
@model PolicyTracker.DomainModel.Common.UserFilter

<script type="text/ecmascript">
    $(document).ready(function () {
        $("form#UserFilterForm").find("#Name").val($("#WLMyFilter option:selected").text());
    });
</script>

<form id="UserFilterForm" class="oraForm">
    <div class="row">
        @Html.ValidationSummary()
    </div>

    @Html.HiddenFor(m => Model.UserId)
    @Html.HiddenFor(m => Model.Expression)

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary borderless">
                <div class="panel-body gray">
                    <div class="form-group">
                        <label>Name</label>
                        <i class="btn btn-danger reqField RFD hidden" data-dec-field="PolicyType">D</i>
                        @Html.TextBoxFor(m => Model.Name, new { @class = "form-control" })
                    </div>
                    
                    <div class="form-group">
                        <label>For Month</label>
                        <select id="MonthFilter" name="MonthFilter" class="form-control">
                            <option value="0"></option>
                            <option value="1">Current</option>
                            <option value="2">Next</option>
                            <option value="3">Month After Next</option>
                        </select>
                        <p class="help-block">If selected updates the filter to also filter by the risk effective date in the desired month. 
                            (Ex. Next Month would mean risks with effective date in @System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(DateTime.Now.AddMonths(1).Month))

                        </p>
                    </div>

                    @*<div class="form-group">
                        <label>Month Range</label>
                        <select id="MonthRangeFilter" name="MonthRangeFilter" class="form-control">
                            <option value="0"></option>
                            <option value="2">2 Months (60 days)</option>
                            <option value="3">3 Months (90 days)</option>
                        </select>
                        <p class="help-block">If user filter contains effecitve date. This will default the effective date filter up to 3 months out from the current month.</p>
                    </div>*@

                    @Html.Label("Filter:")
                    <span style="clear:both;float:left">@Model.Expression</span>
                </div>
            </div>
        </div>
    </div>
</form>

Policy Tracker/Policy Tracker/Views/Home/UserFilters.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        $("#WLMyFilter").change(function () {
            var filter = $("#WLMyFilter").val();
            grid = ASPxClientControl.GetControlCollection().GetByName('WorkingListGrid');
            grid.ApplyFilter(filter);
        });

        $("#DeleteMyFilter").click(function () {
            var userId = $("#CurrUserId").val();
            var filterName = $("#WLMyFilter option:selected").text();
            ora.Dialog.Confirm({
                id: "ConfirmFilterDelete",
                message: "Are you sure you want to delete filter'" + filterName + "'",
                AcceptCallback: function () {
                    ora.Ajax.Ajax({
                        url: "policytracker/Home/DeleteFilterSetting?userId=" + userId + "&filterName=" + filterName,
                        dataType: "HTML",
                        type: "DELETE",
                        successCallback: function (data) { $("#UserFilterPanel").html(data); }
                    });
                },
            })

        });
    });
</script>

<div class="form-group">
    <label class="col-lg-2 col-sm-2 control-label">Filters:</label>
    <div class="col-lg-10 col-sm-10">
        <div class="input-group input-group-sm">
            @Html.DropDownList("WLMyFilter", new SelectList(ViewBag.MyFilters, "Expression", "Name"), "", new { @class = "form-control input-sm", @title = "Apply previously saved filters you have created" })
            <span class="input-group-btn">
                <button id="DeleteMyFilter" type="button" class="btn btn-danger" title="Delete Selected Filter"><i class="fa fa-trash-o"></i></button>
            </span>
        </div>
    </div>
</div>